[package]
name = "fake-ua"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.1"
serde_json = "1.0.2"
serde = { version = "1.0.152", features = ["derive"] }